### ISSUE TITLE
Fix the style sheets so that the pdf icon gets vertical aligned

### ISSUE THREAD

**Issue by jmeile** [jmeile/agreedisclaimer#1]
It would be nice to move the pdf icon down or perhaps centering it. I tried different things with css, but none of them moved the icon :-(
![css_fix](https://cloud.githubusercontent.com/assets/2944439/9106520/28133dde-3c21-11e5-8c40-38087ffa28a5.png)

**Comment by Uesofilm** [comment]
I just tried and got it work!
I think you only need to add those lines to your stylesheet:

``` css
#agreedisclaimerPdfLink {
    display: inline-block;
    vertical-align: bottom;
}
```
